### ISSUE TITLE
issue with agile_grasp2/GraspMsg.h

### ISSUE THREAD

**Issue by flyyflyy** [atenpas/agile_grasp2#1]
Hello, I'm new in the grasping world and I discovered today the new version of agile grasp. During the compilation I have the following error message : 

/home/profile/catkin_ws/src/agile_grasp2/include/agile_grasp2/grasp_hypothesis.h:52:35: fatal error: agile_grasp2/GraspMsg.h: No such file or directory
 #include <agile_grasp2/GraspMsg.h>

I searched GraspMsg.h in the package without success. Is there an other solution ? Thanks in advance

**Comment by gwding** [comment]
I myself didn't run into that problem when trying this package.. GraspMsg.h should be generated from GraspMsg.msg when you run catkin_make

**Comment by atenpas** [comment]
I've never seen this error. You could maybe try this:
```
catkin_make clean
catkin_make --pkg agile_grasp2
```

**Comment by flyyflyy** [comment]
Thanks for your replies. I tried these two commands but that doesn't correct the problem. I remark that there is no add_dependencies in the CMakeLists.txt. Is it normal ?

**Comment by mlauret** [comment]
Hello people, 

After working a bit with @flyyflyy  (coworker), I found that 2 node (cloud_camera and grasp_hypothesis) use same-package-defined message. One problem that might occur is that the messages are built after these 2 nodes. With the dependencies added, the message will be automatically built before the nodes.

The problem doesn't seem to appear for you, @gwding and @atenpas , as maybe your message are already built somewhere in your workspace, or you build your workspace with the option -j1 (only one job at once), and the message are build first by chance :)

You can check this constrain in this documentation (at the line : "If you have a package which builds messages and/or services as well as executables that use them..." ) : 

http://wiki.ros.org/catkin/CMakeLists.txt#Important_Prerequisites.2BAC8-Constraints

Hope that help :)
