### ISSUE TITLE
Request for testing point cloud file

### ISSUE THREAD

**Issue by yaozr** [atenpas/agile_grasp2#3]
Hi:

Is it possible to provide some testing point cloud file PCD that could be used immediately. I hope I did not miss it somewhere...

This would help the study a lot, its not so handy to build one in short time for me  :(

Thx in advance.

BR

Yaozr

**Comment by atenpas** [comment]
I'm planning to make point cloud data available somewhere (certainly not on github to avoid long pulls). For now, maybe you can try this one: https://github.com/atenpas/handle_detector/tree/master/data

**Comment by yaozr** [comment]
Many thx
