### ISSUE TITLE
Where Eye-Arm calibration is done?

### ISSUE THREAD

**Issue by yaozr** [atenpas/agile_grasp2#4]
It is not very clear to me how the 3D camera (asus xtion pro) is calibrated with robot arm, would appreciate if you could refer to the place where the calibration is done.

What's more if we use another ROS enabled robot instead of yours, could you pls give tips forward?

Many thanks.

Yaozr

**Comment by atenpas** [comment]
Maybe you can have a look at some ROS packages that help with calibration, e.g., https://github.com/delftrobotics/camera_pose_calibration

What robot do you use?

**Comment by yaozr** [comment]
I use a Kuka KR6, many thanks for tips.
