### ISSUE TITLE
A question about your program.

### ISSUE THREAD

**Issue by pyni** [atenpas/agile_grasp2#5]
Hello, i have read your code and learnt a lot from it. Thanks your code.
Here i am also doing a grasp with UR5 with eye-in-hand calibration.
Could you tell me that which package of eye-in-hand calibration did you use in your experiment?
I find your calibration perform very well in your grasp.
Thank you.

**Comment by atenpas** [comment]
No package. We calculate the transform manually (by measuring). I would probably try http://wiki.ros.org/visp_hand2eye_calibration but I do not have experience with it.

**Comment by pyni** [comment]
Thanks for your reply！
And i have another two question:
1.in your paper,you used a network like lenet5.why you choose this network?how about alexnet or autoencoder?
2.your paper uses infinitam v2, and i wonder whether you use the default rgb and depth parameters in openni? or you calibrate the new parameters(rgb+depth) for the input of infinitam v2?
Thank you!

**Comment by atenpas** [comment]
1. Lenet is sufficient to solve the problem with a good accuracy. It's a 2-class problem, Lenet can already solve problems with 5x as many classes as that, and Alexnet can solve problems with many more classes.
2. We did not calibrate, and we only use depth data from a _structure.io_ sensor.

**Comment by pyni** [comment]
Thanks for your replies.
