### ISSUE TITLE
catkin_make to compile the package, get some error

### ISSUE THREAD

**Issue by emigmo** [atenpas/agile_grasp2#6]
all the caffe (build though cmake .. -DBUILD_SHARED_LIB=ON,and make successfully)
but when I catkin_make the package ,get following error:

CMake Error at agile_grasp2/CMakeLists.txt:164 (target_link_libraries):
  Attempt to add link library
  "/usr/lib/x86_64-linux-gnu/libopencv_ml.so.2.4.8" to target "plot" which is
  not built in this directory

alway can't complie the "plot" target.
I don't know if only the "plot"  target go wrong.
help me

**Comment by james2254** [comment]
@emigmo ,hello, I have the same problem ,how you solve this problem?
