### ISSUE TITLE
Point cloud Topic can't into callback function

### ISSUE THREAD

**Issue by emigmo** [atenpas/agile_grasp2#7]
Hi atenpas,
    So far, I want to use my a KinectV2 to get the cloud 
    So,I change your code the topic name from ""/camera/depth_registered/points" to 
    my own point cloud topic "/kinect2/hd/point",
    But,I can't get into the callback function "cloud_callback"
   What's wrong with me?

**Comment by atenpas** [comment]
Are there messages on the topic? What does _rostopic bw /kinect2/hd/point_ give?

**Comment by emigmo** [comment]
The topic "/kinect2/hd/point" is published by kinect directly.
![1](https://cloud.githubusercontent.com/assets/10398640/20140683/6fa9dc22-a6c7-11e6-886a-5346dcfd0c5d.png)
 And I think the topic type is right for the cloud_callback function,
but I can't into the callback function and there are no subcriber for the topic 
thank you in advance!

**Comment by emigmo** [comment]
Sorry,I have solved the problem! thank you

**Comment by balloch** [comment]
interested to know how you solved the problem, same here
