### ISSUE TITLE
Issue building (PCL-related likely)

### ISSUE THREAD

**Issue by balloch** [atenpas/agile_grasp2#9]
Hello! I am having issues building the package, specifically with the call to  
`pcl::search::KdTree<pcl::PointXYZRGBA>::KdTree(bool)`. I know I have PCL built and I have packages using it, so this is a bit perplexing. Would love to use your software, so let me know if you have any advice. cmake output attached. Thanks!

-Jon

[catkin_make_output3.txt](https://github.com/atenpas/agile_grasp2/files/630093/catkin_make_output3.txt)

**Comment by balloch** [comment]
as an additional point, I recently "upgraded pcl" (brought it up to the current version) with the following commands:


    `cd ~/Software
    git clone https://github.com/PointCloudLibrary/pcl.git
    cd pcl && mkdir build && cd build
    cmake ..
    make -j2
    sudo make -j2 install`


could this be having the effect

**Comment by atenpas** [comment]
I don't really maintain this package anymore. Would you mind switching to https://github.com/atenpas/gpd?

**Comment by balloch** [comment]
Not at all! 😊 been looking at it since you mentioned it at RSS in fact
